// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.9
// source: tech/storezhang/dnsabre/core/vo/cache.proto

package vo

import (
	kernel "github.com/dnsabre/core/kernel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 缓存
type Cache struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 标识
	Id int64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	// 类型
	Type kernel.CacheType `protobuf:"varint,5,opt,name=type,proto3,enum=tech.storezhang.dnsabre.core.kernel.CacheType" json:"type,omitempty"`
}

func (x *Cache) Reset() {
	*x = Cache{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tech_storezhang_dnsabre_core_vo_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cache) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cache) ProtoMessage() {}

func (x *Cache) ProtoReflect() protoreflect.Message {
	mi := &file_tech_storezhang_dnsabre_core_vo_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cache.ProtoReflect.Descriptor instead.
func (*Cache) Descriptor() ([]byte, []int) {
	return file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescGZIP(), []int{0}
}

func (x *Cache) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cache) GetType() kernel.CacheType {
	if x != nil {
		return x.Type
	}
	return kernel.CacheType(0)
}

var File_tech_storezhang_dnsabre_core_vo_cache_proto protoreflect.FileDescriptor

var file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x74, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e,
	0x67, 0x2f, 0x64, 0x6e, 0x73, 0x61, 0x62, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76,
	0x6f, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x74,
	0x65, 0x63, 0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x64,
	0x6e, 0x73, 0x61, 0x62, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x6f, 0x1a, 0x34,
	0x74, 0x65, 0x63, 0x68, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2f,
	0x64, 0x6e, 0x73, 0x61, 0x62, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x65, 0x72,
	0x6e, 0x65, 0x6c, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x05, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x42, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x74, 0x65,
	0x63, 0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x2e, 0x64, 0x6e,
	0x73, 0x61, 0x62, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x6b, 0x65, 0x72, 0x6e, 0x65,
	0x6c, 0x2e, 0x43, 0x61, 0x63, 0x68, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x42, 0x42, 0x0a, 0x1f, 0x74, 0x65, 0x63, 0x68, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x7a,
	0x68, 0x61, 0x6e, 0x67, 0x2e, 0x64, 0x6e, 0x73, 0x61, 0x62, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x76, 0x6f, 0x50, 0x01, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x6e, 0x73, 0x61, 0x62, 0x72, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f,
	0x76, 0x6f, 0x3b, 0x76, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescOnce sync.Once
	file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescData = file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDesc
)

func file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescGZIP() []byte {
	file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescOnce.Do(func() {
		file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescData)
	})
	return file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDescData
}

var file_tech_storezhang_dnsabre_core_vo_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tech_storezhang_dnsabre_core_vo_cache_proto_goTypes = []interface{}{
	(*Cache)(nil),         // 0: tech.storezhang.dnsabre.core.vo.Cache
	(kernel.CacheType)(0), // 1: tech.storezhang.dnsabre.core.kernel.CacheType
}
var file_tech_storezhang_dnsabre_core_vo_cache_proto_depIdxs = []int32{
	1, // 0: tech.storezhang.dnsabre.core.vo.Cache.type:type_name -> tech.storezhang.dnsabre.core.kernel.CacheType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tech_storezhang_dnsabre_core_vo_cache_proto_init() }
func file_tech_storezhang_dnsabre_core_vo_cache_proto_init() {
	if File_tech_storezhang_dnsabre_core_vo_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tech_storezhang_dnsabre_core_vo_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cache); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tech_storezhang_dnsabre_core_vo_cache_proto_goTypes,
		DependencyIndexes: file_tech_storezhang_dnsabre_core_vo_cache_proto_depIdxs,
		MessageInfos:      file_tech_storezhang_dnsabre_core_vo_cache_proto_msgTypes,
	}.Build()
	File_tech_storezhang_dnsabre_core_vo_cache_proto = out.File
	file_tech_storezhang_dnsabre_core_vo_cache_proto_rawDesc = nil
	file_tech_storezhang_dnsabre_core_vo_cache_proto_goTypes = nil
	file_tech_storezhang_dnsabre_core_vo_cache_proto_depIdxs = nil
}
